apiVersion: v1
kind: Pod
metadata:
  name: httpx
  labels:
    name: httpx
spec:
  containers:
  - name: httpx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
