apiVersion: v1
kind: Pod
metadata:
  name: httpx
  labels:
    name: httpx
spec:
  containers:
  - name: httpx
    image: 853701244726.dkr.ecr.us-west-2.amazonaws.com/httpx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  
