apiVersion: batch/v1
kind: Job
metadata:
  name: httpx
spec:
  template:
    spec:
      containers:
      - name: httpx
        image: 853701244726.dkr.ecr.us-west-2.amazonaws.com/httpx
        command: ["httpx", "-h"]
      restartPolicy: Never
  backoffLimit: 4
