apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: httpx
build:
  artifacts:
  - image: nginx
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests.yaml
